# Generated by Django 2.2.19 on 2021-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='tables/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=5)),
                ('t', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ran', models.DecimalField(decimal_places=2, max_digits=4)),
                ('td', models.DecimalField(decimal_places=1, max_digits=3)),
                ('atm_pres', models.IntegerField()),
                ('wind_dir', models.TextField(blank=True)),
                ('wind_speed', models.TextField(blank=True)),
                ('cloudiness', models.TextField(blank=True)),
                ('h', models.PositiveIntegerField()),
                ('vv', models.TextField(blank=True)),
                ('wconditions', models.CharField(max_length=100)),
            ],
        ),
    ]
