# Generated by Django 2.2.19 on 2021-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210308_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtable',
            name='document',
            field=models.FileField(upload_to='tables/%Y/%m/%d'),
        ),
    ]
