# Generated by Django 2.2.19 on 2021-03-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210308_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadTable',
        ),
        migrations.AlterField(
            model_name='weathertable',
            name='cloudiness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathertable',
            name='vv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathertable',
            name='wconditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathertable',
            name='wind_dir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathertable',
            name='wind_speed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
