# Generated by Django 2.2.19 on 2021-03-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210309_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertable',
            name='ran',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weathertable',
            name='t',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weathertable',
            name='td',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
