# Generated by Django 2.2.19 on 2021-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20210309_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertable',
            name='h',
            field=models.TextField(blank=True, null=True),
        ),
    ]
