# Generated by Django 2.2.19 on 2021-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20210309_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathertable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weathertable',
            name='time',
        ),
        migrations.AddField(
            model_name='weathertable',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
