# Generated by Django 2.2.19 on 2021-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20210311_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertable',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
